package poker;

import java.util.HashMap;
import java.util.Map;

public class preFlopHandValue {
    private static Map<PreFlopValue, Integer> preFlopHands = new HashMap<>();
    public int handValue;

    private void populateHandMap() {
        preFlopHands.put(new PreFlopValue(14, 14, 0), 0);
        preFlopHands.put(new PreFlopValue(14, 13, 1), 2);
        preFlopHands.put(new PreFlopValue(14, 12, 1), 2);
        preFlopHands.put(new PreFlopValue(14, 11, 1), 3);
        preFlopHands.put(new PreFlopValue(14, 10, 1), 5);
        preFlopHands.put(new PreFlopValue(14, 9, 1), 8);
        preFlopHands.put(new PreFlopValue(14, 8, 1), 10);
        preFlopHands.put(new PreFlopValue(14, 7, 1), 13);
        preFlopHands.put(new PreFlopValue(14, 6, 1), 14);
        preFlopHands.put(new PreFlopValue(14, 5, 1), 12);
        preFlopHands.put(new PreFlopValue(14, 4, 1), 14);
        preFlopHands.put(new PreFlopValue(14, 3, 1), 14);
        preFlopHands.put(new PreFlopValue(14, 2, 1), 17);
        preFlopHands.put(new PreFlopValue(14, 13, 0), 5);
        preFlopHands.put(new PreFlopValue(13, 13, 0), 1);
        preFlopHands.put(new PreFlopValue(13, 12, 1), 3);
        preFlopHands.put(new PreFlopValue(13, 11,1), 3);
        preFlopHands.put(new PreFlopValue(13, 10, 1), 6);
        preFlopHands.put(new PreFlopValue(13, 9, 1), 10);
        preFlopHands.put(new PreFlopValue(13, 8, 1), 16);
        preFlopHands.put(new PreFlopValue(13, 7, 1), 19);
        preFlopHands.put(new PreFlopValue(13, 6, 1), 24);
        preFlopHands.put(new PreFlopValue(13, 5, 1), 25);
        preFlopHands.put(new PreFlopValue(13, 4, 1), 25);
        preFlopHands.put(new PreFlopValue(13, 3, 1), 26);
        preFlopHands.put(new PreFlopValue(13, 2, 1), 26);
        preFlopHands.put(new PreFlopValue(14, 12, 0), 8);
        preFlopHands.put(new PreFlopValue(13, 12, 0), 9);
        preFlopHands.put(new PreFlopValue(12, 12, 0), 1);
        preFlopHands.put(new PreFlopValue(12, 11, 1), 5);
        preFlopHands.put(new PreFlopValue(12, 10, 1), 6);
        preFlopHands.put(new PreFlopValue(12, 9, 1), 10);
        preFlopHands.put(new PreFlopValue(12, 8, 1), 19);
        preFlopHands.put(new PreFlopValue(12, 7, 1), 26);
        preFlopHands.put(new PreFlopValue(12, 6, 1), 28);
        preFlopHands.put(new PreFlopValue(12, 5, 1), 29);
        preFlopHands.put(new PreFlopValue(12, 4, 1), 29);
        preFlopHands.put(new PreFlopValue(12, 3, 1), 30);
        preFlopHands.put(new PreFlopValue(12, 2, 1), 31);
        preFlopHands.put(new PreFlopValue(14, 11, 0), 12);
        preFlopHands.put(new PreFlopValue(13, 11, 0), 14);
        preFlopHands.put(new PreFlopValue(12, 11, 0), 15);
        preFlopHands.put(new PreFlopValue(11, 11, 0), 2);
        preFlopHands.put(new PreFlopValue(11, 10, 1), 6);
        preFlopHands.put(new PreFlopValue(11, 9, 1), 11);
        preFlopHands.put(new PreFlopValue(11, 8, 1), 17);
        preFlopHands.put(new PreFlopValue(11, 7, 1), 27);
        preFlopHands.put(new PreFlopValue(11, 6, 1), 33);
        preFlopHands.put(new PreFlopValue(11, 5, 1), 35);
        preFlopHands.put(new PreFlopValue(11, 4, 1), 37);
        preFlopHands.put(new PreFlopValue(11, 3, 1), 37);
        preFlopHands.put(new PreFlopValue(11, 2, 1), 38);
        preFlopHands.put(new PreFlopValue(14, 10, 0), 18);
        preFlopHands.put(new PreFlopValue(13, 10, 0), 20);
        preFlopHands.put(new PreFlopValue(12, 10, 0), 22);
        preFlopHands.put(new PreFlopValue(11, 10, 0), 21);
        preFlopHands.put(new PreFlopValue(10, 10, 0), 4);
        preFlopHands.put(new PreFlopValue(10, 9, 1), 10);
        preFlopHands.put(new PreFlopValue(10, 8, 1), 16);
        preFlopHands.put(new PreFlopValue(10, 7, 1), 25);
        preFlopHands.put(new PreFlopValue(10, 6, 1), 31);
        preFlopHands.put(new PreFlopValue(10, 5, 1), 40);
        preFlopHands.put(new PreFlopValue(10, 4, 1), 40);
        preFlopHands.put(new PreFlopValue(10, 3, 1), 41);
        preFlopHands.put(new PreFlopValue(10, 2, 1), 41);
        preFlopHands.put(new PreFlopValue(14, 9, 0), 32);
        preFlopHands.put(new PreFlopValue(13, 9, 0), 35);
        preFlopHands.put(new PreFlopValue(12, 9, 0), 36);
        preFlopHands.put(new PreFlopValue(11, 9, 0), 34);
        preFlopHands.put(new PreFlopValue(10, 9, 0), 31);
        preFlopHands.put(new PreFlopValue(9, 9, 0), 7);
        preFlopHands.put(new PreFlopValue(9, 8, 1), 17);
        preFlopHands.put(new PreFlopValue(9, 7, 1), 24);
        preFlopHands.put(new PreFlopValue(9, 6, 1), 29);
        preFlopHands.put(new PreFlopValue(9, 5, 1), 38);
        preFlopHands.put(new PreFlopValue(9, 4, 1), 47);
        preFlopHands.put(new PreFlopValue(9, 3, 1), 47);
        preFlopHands.put(new PreFlopValue(9, 2, 1), 49);
        preFlopHands.put(new PreFlopValue(14, 8, 0), 39);
        preFlopHands.put(new PreFlopValue(13, 8, 0), 50);
        preFlopHands.put(new PreFlopValue(12, 8, 0), 53);
        preFlopHands.put(new PreFlopValue(11, 8, 0), 48);
        preFlopHands.put(new PreFlopValue(10, 8, 0), 43);
        preFlopHands.put(new PreFlopValue(9, 8, 0), 42);
        preFlopHands.put(new PreFlopValue(8, 8, 0), 9);
        preFlopHands.put(new PreFlopValue(8, 7, 1), 21);
        preFlopHands.put(new PreFlopValue(8, 6, 1), 27);
        preFlopHands.put(new PreFlopValue(8, 5, 1), 33);
        preFlopHands.put(new PreFlopValue(8, 4, 1), 40);
        preFlopHands.put(new PreFlopValue(8, 3, 1), 53);
        preFlopHands.put(new PreFlopValue(8, 2, 1), 54);
        preFlopHands.put(new PreFlopValue(14, 7, 0), 45);
        preFlopHands.put(new PreFlopValue(13, 7, 0), 57);
        preFlopHands.put(new PreFlopValue(12, 7, 0), 66);
        preFlopHands.put(new PreFlopValue(11, 7, 0), 64);
        preFlopHands.put(new PreFlopValue(10, 7, 0), 59);
        preFlopHands.put(new PreFlopValue(9, 7, 0), 55);
        preFlopHands.put(new PreFlopValue(8, 7, 0), 52);
        preFlopHands.put(new PreFlopValue(7, 7, 0), 12);
        preFlopHands.put(new PreFlopValue(7, 6, 1), 25);
        preFlopHands.put(new PreFlopValue(7, 5, 1), 28);
        preFlopHands.put(new PreFlopValue(7, 4, 1), 37);
        preFlopHands.put(new PreFlopValue(7, 3, 1), 45);
        preFlopHands.put(new PreFlopValue(7, 2, 1), 56);
        preFlopHands.put(new PreFlopValue(14, 6, 0), 51);
        preFlopHands.put(new PreFlopValue(13, 6, 0), 60);
        preFlopHands.put(new PreFlopValue(12, 6, 0), 71);
        preFlopHands.put(new PreFlopValue(11, 6, 0), 80);
        preFlopHands.put(new PreFlopValue(10, 6, 0), 74);
        preFlopHands.put(new PreFlopValue(9, 6, 0), 68);
        preFlopHands.put(new PreFlopValue(8, 6, 0), 61);
        preFlopHands.put(new PreFlopValue(7, 6, 0), 57);
        preFlopHands.put(new PreFlopValue(6, 6, 0), 16);
        preFlopHands.put(new PreFlopValue(6, 5, 1), 27);
        preFlopHands.put(new PreFlopValue(6, 4, 1), 29);
        preFlopHands.put(new PreFlopValue(6, 3, 1), 38);
        preFlopHands.put(new PreFlopValue(6, 2, 1), 49);
        preFlopHands.put(new PreFlopValue(14, 5, 0), 44);
        preFlopHands.put(new PreFlopValue(13, 5, 0), 63);
        preFlopHands.put(new PreFlopValue(12, 5, 0), 75);
        preFlopHands.put(new PreFlopValue(11, 5, 0), 82);
        preFlopHands.put(new PreFlopValue(10, 5, 0), 89);
        preFlopHands.put(new PreFlopValue(9, 5, 0), 83);
        preFlopHands.put(new PreFlopValue(8, 5, 0), 73);
        preFlopHands.put(new PreFlopValue(7, 5, 0), 65);
        preFlopHands.put(new PreFlopValue(6, 5, 0), 58);
        preFlopHands.put(new PreFlopValue(5, 5, 0), 20);
        preFlopHands.put(new PreFlopValue(5, 4, 1), 28);
        preFlopHands.put(new PreFlopValue(5, 3, 1), 32);
        preFlopHands.put(new PreFlopValue(5, 2, 1), 39);
        preFlopHands.put(new PreFlopValue(14, 4,0), 46);
        preFlopHands.put(new PreFlopValue(13, 4, 0), 67);
        preFlopHands.put(new PreFlopValue(12, 4, 0), 76);
        preFlopHands.put(new PreFlopValue(11, 4, 0), 85);
        preFlopHands.put(new PreFlopValue(10, 4, 0), 90);
        preFlopHands.put(new PreFlopValue(9, 4, 0), 95);
        preFlopHands.put(new PreFlopValue(8, 4, 0), 88);
        preFlopHands.put(new PreFlopValue(7, 4, 0), 78);
        preFlopHands.put(new PreFlopValue(6, 4, 0), 70);
        preFlopHands.put(new PreFlopValue(5, 4, 0), 62);
        preFlopHands.put(new PreFlopValue(4, 4, 0), 23);
        preFlopHands.put(new PreFlopValue(4, 3, 1), 36);
        preFlopHands.put(new PreFlopValue(4, 2, 1), 41);
        preFlopHands.put(new PreFlopValue(14, 3, 0), 49);
        preFlopHands.put(new PreFlopValue(13, 3, 0), 67);
        preFlopHands.put(new PreFlopValue(12, 3, 0), 77);
        preFlopHands.put(new PreFlopValue(11, 3, 0), 86);
        preFlopHands.put(new PreFlopValue(10, 3, 0), 92);
        preFlopHands.put(new PreFlopValue(9, 3, 0), 96);
        preFlopHands.put(new PreFlopValue(8, 3, 0), 98);
        preFlopHands.put(new PreFlopValue(7, 3, 0), 93);
        preFlopHands.put(new PreFlopValue(6, 3, 0), 81);
        preFlopHands.put(new PreFlopValue(5, 3, 0), 72);
        preFlopHands.put(new PreFlopValue(4, 3, 0), 76);
        preFlopHands.put(new PreFlopValue(3, 3, 0), 23);
        preFlopHands.put(new PreFlopValue(3, 2, 1), 46);
        preFlopHands.put(new PreFlopValue(14, 2, 0), 54);
        preFlopHands.put(new PreFlopValue(13, 2, 0), 69);
        preFlopHands.put(new PreFlopValue(12, 2, 0), 79);
        preFlopHands.put(new PreFlopValue(11, 2, 0), 87);
        preFlopHands.put(new PreFlopValue(10, 2, 0), 94);
        preFlopHands.put(new PreFlopValue(9, 2, 0), 97);
        preFlopHands.put(new PreFlopValue(8, 2, 0), 99);
        preFlopHands.put(new PreFlopValue(7, 2, 0), 100);
        preFlopHands.put(new PreFlopValue(6, 2, 0), 95);
        preFlopHands.put(new PreFlopValue(5, 2, 0), 84);
        preFlopHands.put(new PreFlopValue(4, 2, 0), 86);
        preFlopHands.put(new PreFlopValue(3, 2, 0), 91);
        preFlopHands.put(new PreFlopValue(2, 2, 0), 24);
    }


    public preFlopHandValue(PreFlopValue handValue){
        populateHandMap();
        int value = preFlopHands.get(handValue);
        this.handValue = value;
    }    
}